<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>

    <TargetFrameworks>net10.0;net9.0;net8.0;net7.0;netstandard2.0</TargetFrameworks>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>net.erlenddahl.ConsoleUtilities</PackageId>
    <RootNamespace>net.erlenddahl.ConsoleUtilities</RootNamespace>
    <Title>Console Utilities</Title>
    <Authors>Erlend Dahl</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/erlenddahl/extensions</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageVersion>1.0.1</PackageVersion>

  </PropertyGroup>

  <!-- Let SDK include source files implicitly to avoid duplicate Compile items -->
  <PropertyGroup>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>