<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyTitle>ConsoleUtilities.Tests</AssemblyTitle>
    <Product>ConsoleUtilities.Tests</Product>
    <Copyright>Copyright ©  2018</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ConsoleUtilities\ConsoleUtilities.csproj" />
  </ItemGroup>
</Project>